### ISSUE TITLE
how to hook printf function

### ISSUE THREAD

**Issue by katatunix** [Demion/nodevfee#20]
Not an issue related to your wonderful tool, I just want to know how to hook the `printf` function. 

What I am doing is:

```
int (__stdcall *printfOriginal)(char const* const _Format, ...);

int __stdcall printfHook(char const* const _Format, ...)
{
	return (*printfOriginal)("haha");
}
...
result = MH_CreateHookApi(L"kernel32.dll", "printf", printfHook, (void**) &printfOriginal);
```

But the `result` is always an error value. I tried both `kernel32.dll` and `msvcrt.dll`.

**Comment by Demion** [comment]
`printf` is not exported by `kernel32.dll` or `msvcrt.dll`, as far as I know. It should be part of standard C library and can even be linked "inside exe" if static runtime library linking is selected (`/MT` flag for Visual Studio). Otherwise (dynamic runtime library linking) it might be in some library like `api-ms-win-crt-stdio-l1-1-0.dll` or other dll for different C runtime library version (depends on compiler). Also names might be different as `__stdio_common_vfprintf` or something else, you need to figure it out by yourself.

This tool might help (choose load from attached to process) - [DLL Export Viewer](http://www.nirsoft.net/utils/dll_export_viewer.html)

**Comment by katatunix** [comment]
Yes, it is exactly the `__stdio_common_vfprintf` function. The `printf` in `stdio.h` is an inline function and eventually calls `__stdio_common_vfprintf`. The exact dll file is `ucrtbase.dll`.

I managed to hook that function.

Thank you very much.
