### ISSUE TITLE
I want it to support etc，so thanks

### ISSUE THREAD

**Issue by bigbeef** [Demion/nodevfee#24]

**Comment by Demion** [comment]
ETC - Ethereum Classic? So does is not work now?

**Comment by eyeflip** [comment]
I tried ETC using claymore 10.0 with nodevfee.exe at the beginning and it just closes right away. any ideas? thanks

**Comment by Demion** [comment]
What is your bat file?

**Comment by eyeflip** [comment]
setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
nodevfee.exe ethdcrminer64.exe -epool etc-us-east1.nanopool.org:19999 -ewal 0xb0c5db0f2d31593a9d38c9e48905152271423670.worker1/yusufjunk@gmail.com -epsw x

**Comment by Demion** [comment]
Attach your claymore log and `nodevfeeLog.txt` (create empty text file `nodevfeeLog.txt` before running miner).

**Comment by eyeflip** [comment]
I created the nodevfeeLog.txt and it started and then restarted and I believe its working. I will know for sure when it tries to run the dev fee.  can I do this with pirl or ella or any other coin running through claymore?

**Comment by Demion** [comment]
You most likely will need `nodevfeePools.txt` to redirect ethereum devfee mining pools to your fork pool. Read more about that on main page README. It may still not work though, but you can give it a shot. No other solution so far.

**Comment by eyeflip** [comment]
I'm sorry I don't quite understand how to write the nodevfeePools.txt I looked at the pastebin and it is just a list of pools. I'm really new to this, would you by any chance have a more specific example I could follow. sorry to keep buggin you

**Comment by Demion** [comment]
I think it is pretty clear in README.
```
PoolCount (including main pool N + 1)
MainPoolAddress MainPoolPort (space between address and port not colon)
DevFeePool1Address DevFeePool1Port
DevFeePool2Address DevFeePool2Port
DevFeePoolNAddress DevFeePoolNPort
```

1. line number of pools (including main pool).
2. line your main pool (ETC pool).
3. line and below devfee pools that will be redirected (you can use list from example).

**Comment by eyeflip** [comment]
thanks for all of your help, unfortunately I don't think its working with my PIRL setup, but if you have anymore suggestions, that'd be great.

![screenshot 1](https://user-images.githubusercontent.com/20123912/36054465-3537d802-0dbc-11e8-822f-63bf300560a2.png)

nodevfee.exe EthDcrMiner64.exe -epool stratum+tcp://us-east.pirlpool.eu:8002 -ewal 0xC48B8cb875926C9637e827280d90b9737Cb4D42F  -epsw x -esm 0 -allpools 1 -allcoins exp -gser 2 -eworker rig6 -retrydelay 1 

[1518216438_log.txt](https://github.com/Demion/nodevfee/files/1712708/1518216438_log.txt)

[nodevfeePools.txt](https://github.com/Demion/nodevfee/files/1712709/nodevfeePools.txt)

I tried to attach the nodevfeeLog.txt but it says I cant since its empty.

**Comment by Demion** [comment]
I think you dont need `-allpools 1 -allcoins exp` or try to increase number in `nodevfeePools.txt` and add to the end those pools you see on screenshot.

**Comment by eyeflip** [comment]
Oh so that is how it is supposed to look? all the red errors are normal? the devfee will just keep trying to connect? and any shares found will just go to my pirl wallet? 

I removed the allcoins. and all the pools I have seen it try to connect to are in the nodevfeepools already. thanks for all your help!

![screenshot 2](https://user-images.githubusercontent.com/20123912/36057820-70ccdaf8-0dd9-11e8-9157-3b566246bf0f.png)

[1518228706_log.txt](https://github.com/Demion/nodevfee/files/1712935/1518228706_log.txt)

**Comment by Demion** [comment]
`nodevfeePools.txt` only supported starting from **v0.2.2b**.

**Comment by eyeflip** [comment]
yup I'm a dummy, and I'm assuming the screenshot means its working? thanks for all you time!!

![screenshot 3](https://user-images.githubusercontent.com/20123912/36058722-c9c1e66c-0ded-11e8-9946-5ff40ce89814.png)

**Comment by Demion** [comment]
Seems to work, you better check actual results on your pool for some time. Closed for now.
