### ISSUE TITLE
Claymore version for v0.2.6b

### ISSUE THREAD

**Issue by babydragon89** [Demion/nodevfee#39]
I would like to thank Demion for the contribution. It works great on Claymore v10.0, but I want to know what the latest version of Claymore that v0.2.6b supports is. I've read through some issues/comments and saw that v11 should work fine. Can someone please confirm?

**Comment by TheTexasMiner** [comment]
I have tested it on Claymore v11.0 and v11.2
I monitored it with Wireshark.
Works just fine.

**Comment by Demion** [comment]
Theoretically nodevfee should work on all version including latest 11.2, but
1. Starting from 10.6 or 11.0 users report efficiency decrease using nodevfee, you can try new test verion using WinDivert driver (WFP) instead of dll injection and api hook - divert. More detailes here - https://github.com/Demion/nodevfee/issues/34#issuecomment-369309388
2. Starting from 11.1 devfee use SSL encryption. No solution so far.  More details here - https://github.com/Demion/nodevfee/issues/34#issuecomment-370114352.
